on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 10
            - run: cd packages/core && npm install && tsc
            - run: cd packages/core && npm test
            - run: cd packages/alexa && npm install && cd -
            - run: cd packages/cli && npm install && cd -
