on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    main_branch:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 10
            - run: npx lerna bootstrap
            - run: npm run build
            - run: npm run coverage
            - run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  package: ./packages/core/package.json
              env:
                  INPUT_TOKEN: ""
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  package: ./packages/alexa/package.json
              env:
                  INPUT_TOKEN: ""
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  package: ./packages/cli/package.json
              env:
                  INPUT_TOKEN: ""
